### ISSUE TITLE
State Management

### ISSUE THREAD

**Issue by phoscoder** [JS-Hub-ZW/hackathon-board#35]
Let move to actual Redux library and use  Redux toolkit

**Comment by Ravijhabit** [comment]
Hi @takumade, Can you assign this ticket to me ?
Can you also attach hackoctoberfest labe with this issue ?

**Comment by phoscoder** [comment]
Hello @Ravijhabit 

I did add redux about 3 hours ago, but let update the issues when I wake up, assign labels to them then you can choose what you like to contribute
