### ISSUE TITLE
Cypress Test: Contact Page

### ISSUE THREAD

**Issue by phoscoder** [JS-Hub-ZW/hackathon-board#50]
Write a suite of tests for the home page

It should test if user can view contact page
It should test if user cards
Click hack button button should lead to github

**Comment by Shivansh-22866** [comment]
@takumade assign me this issue

**Comment by phoscoder** [comment]
Hello @Shivansh-22866 assigning you now

**Comment by phoscoder** [comment]
Done

**Comment by Shivansh-22866** [comment]
@takumade I have made a PR, review it once. If any change is needed, kindly suggest me the changes. Also, kindly add "hacktoberfest-accepted" label before merging the PR.

**Comment by phoscoder** [comment]
hacktoberfest-accepted
