### ISSUE TITLE
Hackathon Detail

### ISSUE THREAD

**Issue by phoscoder** [JS-Hub-ZW/hackathon-board#58]
For now hackathon detail(`src/pages/detail/[id].tsx`) is commented out 

![image](https://github.com/user-attachments/assets/39b1abfb-bd8f-4dc4-8f41-78523b55510a)

Rewrite `getStaticPaths` and `getStaticProps`

**getStaticPaths** should generate paths
**getStaticProps** should get a hackathon from events given id

Once that is done successfully we can then recomment Detail page components
![image](https://github.com/user-attachments/assets/19cbada0-81b7-4f49-92d6-1d9e2597a994)

**Comment by Daksh-134** [comment]
Hi @takumade  ,pls assign it to me if issue is still open

**Comment by phoscoder** [comment]
Done
