### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by phoscoder** [JS-Hub-ZW/hackathon-board#9]
What is the hackathon board?
Who created it?
What do its creators do?

**Comment by gtchakama** [comment]
Fixing this now with @RSimmz98

**Comment by phoscoder** [comment]
Unlinked it from the site

**Comment by phoscoder** [comment]
Linked to the site and added a purpose, target audience and team members section

Removed some code that was unclear and uncomplete

Closing this one for now
